export enum NeuesProjekt {
  NEUES_PROJEKT_ANLEGEN = 0,
  IMPORT = 1,
  IMPORT_KONFIGURATION = 2,
  LEITERPLATTE = 3,
  BOM = 4,
  ALTERNATIV = 5,
  VERGLEICHEN = 6,
  ZUSAMMENFASSUNG = 7,
  BESTAETIGEN = 8
}
