export enum QuellenStatus {
  NICHT_GEPRUEFT = 0,
  NICHT_VERFUEGBAR = 1,
  VERFUEGBAR_IN = 2,
  VERFUEGBAR = 3,
  ALTERNATIVE_VERFUEGBAR = 4,
  ALTERNATIVE_NICHT_VERFUEGBAR = 5,
  ALTERNATIVE_VERFUEGBAR_IN = 6
}